export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const LOAD_MORE_LIST_REQUEST = 'LOAD_MORE_LIST_REQUEST';
export const LOAD_MORE_LIST_SUCCESS = 'LOAD_MORE_LIST_SUCCESS';
